services:
  xray:
    image: ghcr.io/xtls/xray-core:latest
    container_name: xray-core
    restart: always
    network_mode: host
    
    volumes:
      - ./config:/etc/xray
      - ./logs:/var/log/xray
      
    environment:
      - TZ=UTC
      - XRAY_LOCATION_ASSET=/usr/local/share/xray/

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"